# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 33b55550076385d8a164c83e7075048ab03fbba39cfc4f1d481f668bb0948f6ab6e9bfa1c91c8e1cbcaff1bef1258d7d7c91b52d1a89e68ba849c57ec4f67a83

test:
  secret_key_base: bb66f99bc41d6c1ed7f8dfcdd43f60af28f5c3407bf4ff0482e37ef2ef83f7037ac3ca6558ed8c00819a7af3c019002af279e88043dda649893b8ac3356b79e5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
